# Generated by Django 3.2.13 on 2022-12-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameGlasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_shape', models.IntegerField()),
                ('id_frame', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShapeFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=50)),
            ],
        ),
    ]
