# Generated by Django 3.2.13 on 2022-12-18 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_frameglasses_recommendation_shapeface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.frameglasses'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='id_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.orders'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='id_frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.frameglasses'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='id_shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.shapeface'),
        ),
    ]
