# Generated by Django 3.2.13 on 2022-12-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_news_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
